### ISSUE TITLE
Add option to select site binding

### ISSUE THREAD

**Issue by dboyanov** [todorm85/Sf-PoSh#115]
When executing site-browse command it would be nice to have the option to select from available bindings and configure which one is the default one.

**Comment by todorm85** [comment]
#107 related

**Comment by todorm85** [comment]
- [ ] fix getting dev url - should find first localhost on http and return it
- [ ] for default behavior
	- [ ] check if default entry is set in config and check if it exists in site and hosts 
	- [ ] should check if project name exists as configuration in website and in hosts
	- [ ] fallback to first found then
- [ ] separate function to choose the default url to use
- [ ] when browsing the site check if it is started

**Comment by todorm85** [comment]
Test cases:
- [ ] - Default site has not been set - returns the last binding
- [ ] - Default site has been set - returns the binding with default site
- [ ] - Default site has been set, but binding was deleted - returns the last binding
- [ ] - Changing the binding removes the hosts file entry and adds a new one, also changes the domain of the current binding

**Comment by todorm85** [comment]
- [ ] - add new API to psd
